### ISSUE TITLE
参数最好加一个block的运行队列

### ISSUE THREAD

**Issue by xuzhongping** [hehe520/CKWeakTimer#1]
参数最好加一个block的执行队列，用来表明回调应该执行在哪个线程，你现在默认就是在子线程执行

**Comment by hehe520** [comment]
对，默认在子线程执行，要操作UI，还是要用户切回 main_queue 啊

**Comment by xuzhongping** [comment]
我觉得让用户直接通过参数去设置应该执行在哪个线程更好，用户也许不知道默认会在子线程执行

**Comment by hehe520** [comment]
对，但是我是模仿nstimer的方法来的，可以新增一个方法设置运行队列的
